---
name: remote-monitor-example
token: eyJhbGciOiJSUzI1NiJ...[kesque pulsar JWT]
slackConfig:
  alertUrl: https://hooks.slack.com/services/[slack alert app]
brokersConfig:
    intervalSeconds: 62
    inclusterRestURL: "https://useast2.aws.kafkaesque.io:8964"
prometheusConfig:
  port: ":8089"
  exposeMetrics: true
k8sConfig:
  enabled: false
pulsarTopicConfig:
  - latencyBudgetMs: 800
    pulsarUrl: pulsar+ssl://useast2.aws.kafkaesque.io:6651
    topicName: persistent://tenant/namespace/latency-test
    payloadSizes: ["15B"]
    intervalSeconds: 20
    numberOfMessages: 1
    alertPolicy:
      Ceiling: 3
      MovingWindowSeconds: 600
      CeilingInMovingWindow: 5

websocketConfig:
  - latencyBudgetMs: 640
    name: websocket_topic_useast2_aws
    intervalSeconds: 60
    cluster: useast2.aws.kafkaesque.io
    topicName: persistent/tenant/namespace/latency-websocket-topic
    scheme: "wss://"
    port: "8001"
